language: objective-c
rvm: 1.9.3

before_install:
  - brew unlink xctool
  - brew update
  - brew install xctool

script:
  - xctool test -workspace iOSUnitTesting/iOSUnitTesting.xcworkspace -scheme iOSUnitTesting -sdk iphonesimulator
